include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    # Riverpod specific
    - always_use_package_imports
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - unnecessary_const
    - unnecessary_new

    # General best practices
    - always_declare_return_types
    - avoid_redundant_argument_values
    - avoid_unnecessary_containers
    - require_trailing_commas
    - sort_child_properties_last
